name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
   # env:
   #   GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
     #   with:
     #     token: ${{ secrets.GH_REPO_TOKEN }} 
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
      - name: Log failed systems to output
        if: steps.check_failed.outputs.has_failures == 'true'
        run: |
         echo "The following systems have failed and require attention:"
         echo "${{ steps.check_failed.outputs.failed_systems }}"
      - name: Update failed_systems.log after notifications
        if: steps.check_failed.outputs.has_failures == 'true'
        run: bash ./update_failed_systems_log.sh
      - name: Commit and Push Logs
        run: |
          git config user.name "test"
          git config user.email "elise-brook.davis-hirst@york.ac.uk"
          git add -A --force logs/
