name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - name: Say hello
        run: echo "Health check running now!"
      # - uses: actions/checkout@v4
      # - name: Run Shell Script
      #   id: shell_script_run
      #   run: bash ./health-check.sh
