name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  health_check_job:
    runs-on: [self-hosted]
    name: Check all sites
    env:
      GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_REPO_TOKEN }} 
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
      - name: Commit and Push Logs
        run: |
          git config user.name "ytubot"
          git config user.email "ytu-developers-group+githubapi@york.ac.uk"
          git add -A --force logs/
          git commit -am "[Automated] Update Health Check Logs" || echo "Nothing to commit"
          git push "https://x-access-token:${{ secrets.GH_REPO_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
      - name: Check for failed systems and trigger email notifications
        run: bash ./notify_failed_systems.sh
      - name: Send email notification for failed systems
        if: success() && hashFiles('logs/email_triggers.txt') != ''
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          subject: "${{ github.repository }} Notification: System Report"
          to: ytu-techsupport-group@york.ac.uk
          from: "${{ github.repository }} <${{ secrets.MAIL_USERNAME }}>"
          reply_to: ytu-techsupport-group@york.ac.uk
          body: |
            The following systems have failed and require attention:
            ${{ steps.shell_script_run.outputs.failed_keys }}
      - name: Update failed_systems.log after notifications
        if: success() && hashFiles('logs/email_triggers.txt') != ''
        run: bash ./update_failed_systems_log.sh
