name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  health_check_job:
    runs-on: [self-hosted]
    name: Check all sites
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TEST_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
      - name: Commit and Push Logs
        run: |
              git config user.name "ytubot"
              git config user.email "ytu-developers-group+githubapi@york.ac.uk"
              git add -A --force logs/
              git commit -am "[Automated] Update Health Check Logs" || echo "Nothing to commit"
              git push "https://x-access-token:${{ secrets.GH_TEST_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
        env:
          GH_TEST_TOKEN: ${{ secrets.APPROVE_README_PAT }}
