name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  health_check_job:
    runs-on: [self-hosted]
    name: Check all sites
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TEST_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
